[providers]
[providers.openapi]
secret_key = "*****"
llm_model = "gpt-4o-mini"
tts_voice = "nove"
sst_model = "whisper-1"
sst_lang = "en"


[providers.livekit]
ws_url = "ws://127.0.0.1:7881"
api_key = "devkey"
secret_key = "secret"
